#!/bin/sh

myip=$(hostname -I | awk '{print$1}')
strapiHealth=$(curl -IL localhost:1337/_health -o /dev/null -w '%{http_code}\n' -s)
isInstalling="true"

if [ $strapiHealth = "204" ]; then 
  isInstalling="false"
fi

cat <<EOF
       Welcome to DigitalOcean's One-Click Strapi Droplet!
   Below are some useful documentation links to get you started
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - Strapi website: https://strapi.io
    - Strapi documentation: https://strapi.io/documentation
    - Your installation: http://$myip
    - Your admin: http://$myip/admin

    Here are some information about your current installation
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - Strapi is installed at /srv/strapi/strapi
    - The Strapi process is running under the strapi user
    - UFW firewall is enabled, all ports are BLOCKED except
      22 (SSH), 80 (HTTP), and 443 (HTTPS)

EOF

if [ $isInstalling = "true" ]; then
  cat <<EOF
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Strapi is still currently being installed, please wait a few
    more minutes.

EOF
fi